export const BOOK_STATISTIC_FETCH_START = "BOOK_STATISTIC_FETCH_START";
export const BOOK_STATISTIC_FETCH_IN_PROGRESS = "BOOK_STATISTIC_FETCH_IN_PROGRESS";
export const BOOK_STATISTIC_FETCH_SUCCESS = "BOOK_STATISTIC_FETCH_SUCCESS";
export const BOOK_STATISTIC_FETCH_ERROR = "BOOK_STATISTIC_FETCH_ERROR";
